// Authentication Flow
export const ACTION_REDIRECT = 'REDIRECT'
export const ACTION_LOGIN = 'LOGIN'
export const ACTION_REGISTER = 'REGISTER'
export const ACTION_UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH'
export const ACTION_LOGIN_PAGE_UNLOADED = 'LOGIN_PAGE_UNLOADED'
export const ACTION_REGISTER_PAGE_UNLOADED = 'REGISTER_PAGE_UNLOADED'

// Home
export const ACTION_UPDATE_FIELD_HOME = 'UPDATE_FIELD_HOME'
export const ACTION_SUBMIT_HOME = 'HOME_SUBMIT'
export const ACTION_HOME_UNLOADED = 'HOME_UNLOADED'

// Search
export const ACTION_UPDATE_FIELD_SEARCH = 'UPDATE_FIELD_SEARCH'
export const ACTION_SUBMIT_SEARCH = 'SEARCH_SUBMIT'
export const ACTION_SEARCH_UNLOADED = 'SEARCH_UNLOADED'

// Property
export const ACTION_PROPERTY_DETAIL_SET = 'PROPERTY_DETAIL_SET'
export const ACTION_UPDATE_FIELD_PROPERTY_DETAIL = 'UPDATE_FIELD_PROPERTY'
export const ACTION_SUBMIT_PROPERTY_DETAIL = 'PROPERTY_SUBMIT'
export const ACTION_PROPERTY_DETAIL_UNLOADED = 'PROPERTY_DETAIL_UNLOADED'
